[package]
name = "directory-traversal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
same-file = "1.0.6"
walkdir = "2.3.2"